### ISSUE TITLE
Time consumption?

### ISSUE THREAD

**Issue by Colezwhy** [theEricMa/ScaleDreamer#4]
Hi, congratulations for the nice work!
But when checking the paper, I found no specific data illustrating the time cost for the optimization based setting.
Would you please give some numbers on that? (I noticed that the setting you used is the same as VSD, what about the time cost?)
Thank you for your great work!

**Comment by theEricMa** [comment]
Hi, yes, we follow the VSD configuration, optimizing for 25,000 iterations. With ASD, each prompt takes 3.5 hours, whereas with VSD, each takes 4.5 hours.

**Comment by Colezwhy** [comment]
> Hi, yes, we follow the VSD configuration, optimizing for 25,000 iterations. With ASD, each prompt takes 3.5 hours, whereas with VSD, each takes 4.5 hours.

Thanks, nice job!
