### ISSUE TITLE
How to conduct a yaml file for pretrianed diffusion model?

### ISSUE THREAD

**Issue by throb081** [theEricMa/ScaleDreamer#5]
Hello，i recently read  your paper and got so interested in it !It's so kind for you to public your code.However ,i want to try other diffusion model instead of sd-v2-base, but i can't find out a way to construct a file like sd-v2-base.yaml,so it would be grateful for me if you can give me some advice !!!Thanks！

**Comment by theEricMa** [comment]
Thank you very much for your interest in our work. We offer the code of ASD with [Stable Diffusion](https://github.com/theEricMa/ScaleDreamer/blob/main/threestudio/models/guidance/stable_diffusion_asd_guidance.py) and [MVDream](https://github.com/theEricMa/ScaleDreamer/blob/main/threestudio/models/guidance/mvdream_asd_guidance.py). You can refer to our code as a guide for implementing other 2D diffusion priors. For any further questions, please let me know.
